# This stuff plots the solution generated by a single run of run_KenyaCoV.jl

ũ = [reshape(u,n,n_s,2) for u in sol_tl.u]
susceptibles = [sum(u[:,1,:])/sum(u) for u in ũ ]
infecteds_A = [sum(u[:,3,:]) for u in ũ ]
infecteds_D = [sum(u[:,4,:]) for u in ũ ]
recovereds = [sum(u[:,5,:])/sum(u) for u in ũ ]
cum_infecteds =  [sum(u[:,7:8,:])/sum(u) for u in ũ ]

plot(sol_tl.t,susceptibles,lab="S")
plot(sol_tl.t,infecteds_A,lab ="I_A")
plot!(sol_tl.t,infecteds_D,lab ="I_D")
plot!(sol_tl.t,recovereds,lab="R")
plot!(sol_tl.t,infecteds_D,lab ="I_D")
plot!(sol_tl.t,cum_infecteds,lab ="cum. I")
